name: keynest
description: A secure hybrid password manager and authenticator.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.5.0
  uuid: ^4.0.0
  base32: ^2.1.3
  json_annotation: ^4.8.1
  meta: ^1.9.1
  clock: ^1.1.1
  image_picker: ^1.0.7
  flutter_secure_storage: ^9.0.0
  idb_shim: ^2.4.1+1
  lottie: ^3.3.2
  http: ^1.2.0
  crypto: ^3.0.3
  local_auth: ^2.1.6
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#0175C2"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
